# Generated by Django 3.2.5 on 2022-06-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='copy_issue_item_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userlog',
            name='copy_issue_item_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
