# Generated by Django 3.2.5 on 2022-06-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_userlog_issue_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='copy_issue_item_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
