# Generated by Django 3.2.5 on 2022-06-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_issueitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='copy_issue_item_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
