# Generated by Django 3.2.5 on 2022-06-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20220605_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='slug',
        ),
    ]
