# Generated by Django 3.2.5 on 2022-06-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_inventory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='copy_issue_category',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
