# Generated by Django 3.2.5 on 2022-06-06 04:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_userlog_copy_issue_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderatorlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=50, unique=True)),
                ('Quantity', models.IntegerField()),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
            ],
        ),
    ]
