# Generated by Django 3.2.5 on 2022-06-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_moderatorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='issueitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='moderatorlog',
            name='Quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='copy_issue_item_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
