# Generated by Django 3.2.5 on 2022-06-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20220607_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Item_name',
            field=models.CharField(max_length=50),
        ),
    ]
