# Generated by Django 3.2.5 on 2022-06-07 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_inventory_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='Quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
