# Generated by Django 3.2.5 on 2022-06-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='quantity_to_be_returned',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
